# Generated by Django 6.0 on 2025-12-10 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name': 'Клуб', 'verbose_name_plural': 'Клубтар'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Іс-шара', 'verbose_name_plural': 'Іс-шаралар'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Мүшелік', 'verbose_name_plural': 'Мүшеліктер'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Хабарландыру', 'verbose_name_plural': 'Хабарландырулар'},
        ),
        migrations.AddField(
            model_name='membership',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ескертпелер'),
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('academic', 'Академиялық'), ('sports', 'Спорттық'), ('cultural', 'Мәдени'), ('technical', 'Техникалық'), ('art', 'Өнер'), ('volunteer', 'Еріктілер'), ('other', 'Басқа')], default='other', max_length=20, verbose_name='Санат'),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Өтініш берген уақыты'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Бекітілген уақыты'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', 'Күтуде'), ('approved', 'Қабылданған'), ('rejected', 'Қабылданбаған')], default='pending', max_length=10, verbose_name='Мәртебесі'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланушы'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clubs.club', verbose_name='Клуб'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жасалған уақыты'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Жасаған'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Хабарландыру'), ('event', 'Іс-шара'), ('membership', 'Мүшелік'), ('general', 'Жалпы'), ('important', 'Маңызды')], default='announcement', max_length=20, verbose_name='Түрі'),
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Тіркелген'), ('attended', 'Қатысқан'), ('absent', 'Қатыспаған')], default='registered', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Іс-шараға қатысу',
                'verbose_name_plural': 'Іс-шараға қатысулар',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, through='clubs.EventAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Қатысушылар'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тақырып')),
                ('content', models.TextField(verbose_name='Хабар')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыты')),
                ('is_read', models.BooleanField(default=False, verbose_name='Оқылған')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Қабылдаушы')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Жіберуші')),
            ],
            options={
                'verbose_name': 'Хабар',
                'verbose_name_plural': 'Хабарлар',
                'ordering': ['-sent_at'],
            },
        ),
    ]
